// $Id: HfsRenderAction.java,v 1.1 2008/05/30 09:14:08 jim Exp $

package us.temerity.pipeline.plugin.HfsRenderAction.v2_4_3;

import us.temerity.pipeline.*; 
import us.temerity.pipeline.plugin.HfsActionUtils; 

import java.lang.*;
import java.util.*;
import java.io.*;

/*------------------------------------------------------------------------------------------*/
/*    H F S   R E N D E R   A C T I O N                                                     */
/*------------------------------------------------------------------------------------------*/

/**
 * Renders a sequences of images directly from a Houdini scene. <P> 
 * 
 * This action provides a convienent method for evaluating a renderer output operator 
 * contained in the source Houdini scene using hscript(1).  The target primary file
 * sequence should contain the images to be rendered.  The frame range (trange f1 f2 f3) and
 * output picture (picture) parameters of this operator will be overridden by the Action 
 * to correspond to the images regenerated by the job. <P> 
 * 
 * The following Houdini output operators are supported by this action:<BR>
 * <DIV style="margin-left: 40px;">
 *   Mantra - The Houdini renderer. <BR>
 *   Wren - The Houdini line renderer. <BR>
 *   RenderMan - RenderMan compliant renderers. <BR>
 *   MentalRay - The MentalRay raytracer. <BR>
 * </DIV> <P> 
 * 
 * See the <A href="http://www.sidefx.com">Houdini</A> documentation for details on the
 * usage and behavior of renderer output operators and hbatch(1).<P> 
 * 
 * This action defines the following single valued parameters: <BR>
 * 
 * <DIV style="margin-left: 40px;">
 *   Houdini Scene <BR>
 *   <DIV style="margin-left: 40px;">
 *     The source node which contains the Houdini scene file to render. <BR> 
 *   </DIV> <BR>
 * 
 *   Renderer <BR>
 *   <DIV style="margin-left: 40px;">
 *     The specific render output OP type being used.  Houdini-8 style output OPs share
 *     a common set of opparams used by this action, while the newer Houdini-9 output 
 *     OPs use uniquely named opparams for things like output file names.  This parameter
 *     is used to select between the following OP types: <BR>
 *     <DIV style="margin-left: 40px;">
 *       H8 Common - Houdini-8 style render output OPs: H8 Mantra, H8 MentalRay, H8 RenderMan
 *                   Object Scene and Wren 1.0
 *       Mantra - Houdini-9 style Mantra output OP.<BR>
 *       MentalRay - Houdini-9 style MentalRay output OP.<BR>
 *       RenderMan - Houdini-9 style RenderMan output OP.
 *     </DIV> <P> 
 *   </DIV> <BR>
 *
 *   Output Operator <BR>
 *   <DIV style="margin-left: 40px;">
 *     The full Houdini path name of the render output operator. <BR>
 *   </DIV> <BR>
 *
 *   Camera Override <BR>
 *   <DIV style="margin-left: 40px;">
 *     Overrides the render camera (if set). <BR> 
 *   </DIV> <BR>
 * 
 *   Use Graphical License<BR> 
 *   <DIV style="margin-left: 40px;">
 *     Whether to use an interactive graphical Houdini license when running hbatch(1).  
 *     Normally, hbatch(1) is run using a non-graphical license (-R option).  A graphical 
 *     license may be required if the site has not obtained any non-graphical licenses.
 *   </DIV> <BR>
 * 
 *   <DIV style="margin-left: 40px;">
 *     Extra Options <BR>
 *     <DIV style="margin-left: 40px;">
 *       Additional hbatch(1) command-line arguments. <BR> 
 *     </DIV> <BR>
 *   </DIV> <P> 
 *   <P> 
 * 
 *   
 *   Pre Render Script <BR>
 *   <DIV style="margin-left: 40px;">
 *     The source node which contains the command script to evaluate before rendering 
 *     begins.  <BR>
 *   </DIV> <BR>
 * 
 *   Post Render Script <BR>
 *   <DIV style="margin-left: 40px;">
 *     The source node which contains the command script to evaluate after rendering 
 *     ends. <BR>
 *   </DIV> <BR>
 * 
 *   Pre Frame Script <BR>
 *   <DIV style="margin-left: 40px;">
 *     The source node which contains the command script to evaluate before rendering each 
 *     frame. <BR>
 *   </DIV> <BR>
 * 
 *   Post Frame Script <BR>
 *   <DIV style="margin-left: 40px;">
 *     The source node which contains the command script to evaluate after rendering each 
 *     frame. <BR>
 *   </DIV> <BR>
 * 
 * </DIV> <P> 
 */
public
class HfsRenderAction
  extends HfsActionUtils
{  
  /*----------------------------------------------------------------------------------------*/
  /*   C O N S T R U C T O R                                                                */
  /*----------------------------------------------------------------------------------------*/
  
  public
  HfsRenderAction() 
  {
    super("HfsRender", new VersionID("2.4.3"), "Temerity",
	  "Renders a sequences of images directly from a Houdini scene.");

    addHoudiniSceneParam();

    {
      ArrayList<String> choices = new ArrayList<String>();
      choices.add(aH8Common);
      choices.add(aMantra);
      choices.add(aMentalRay);
      choices.add(aRenderMan);
    
      ActionParam param = 
        new EnumActionParam
        (aRenderer,
         "The specific render output OP type being used.  Houdini-8 style output OPs share " +
         "a common set of opparams used by this action, while the newer Houdini-9 output " + 
         "OPs use uniquely named opparams for things like output file names.", 
         aH8Common, choices);
      addSingleParam(param);
    }

    addOutputOperatorParam("/out/mantra1"); 
    addCameraOverrideParam(); 
    addUseGraphicalLicenseParam();
    addExtraOptionsParam();

    addPreRenderScriptParam();
    addPostRenderScriptParam();
    addPreFrameScriptParam();
    addPostFrameScriptParam();

    {
      LayoutGroup layout = new LayoutGroup(true);
      layout.addEntry(aHoudiniScene);
      layout.addEntry(aRenderer);
      layout.addEntry(aOutputOperator);
      layout.addEntry(aCameraOverride);
      layout.addSeparator();
      layout.addEntry(aUseGraphicalLicense);
      addExtraOptionsParamToLayout(layout);

      addScriptParamsToLayout(layout); 
      
      setSingleLayout(layout);
    }

    //addSupport(OsType.Windows);
  }

  

  /*----------------------------------------------------------------------------------------*/
  /*   A C T I O N                                                                          */
  /*----------------------------------------------------------------------------------------*/

  /**
   * Construct a {@link SubProcessHeavy SubProcessHeavy} instance which when executed will 
   * fulfill the given action agenda. <P> 
   * 
   * @param agenda
   *   The agenda to be accomplished by the action.
   * 
   * @param outFile 
   *   The file to which all STDOUT output is redirected.
   * 
   * @param errFile 
   *   The file to which all STDERR output is redirected.
   * 
   * @return 
   *   The SubProcess which will fulfill the agenda.
   * 
   * @throws PipelineException 
   *   If unable to prepare a SubProcess due to illegal, missing or imcompatable 
   *   information in the action agenda or a general failure of the prep method code.
   */
  public SubProcessHeavy
  prep
  (
   ActionAgenda agenda,
   File outFile, 
   File errFile 
  )
    throws PipelineException
  { 
    /* target files */ 
    FileSeq targetSeq = 
      new FileSeq(agenda.getTargetPath().toString(), agenda.getPrimaryTarget()); 

    /* houdini scene */ 
    Path source = getHoudiniSceneSourcePath(aHoudiniScene, agenda);

    /* houdini version */ 
    VersionID hvid = getHoudiniVersion(agenda); 

    /* create the temporary Houdini command script */ 
    Path hscript = new Path(createTemp(agenda, "cmd"));
    try {      
      FileWriter out = new FileWriter(hscript.toFile());
    
      String opname = getSingleStringParamValue(aOutputOperator, false);

      writeCameraOverrideOpparm(opname, agenda, out);

      String picture = null; 
      {
        String renderer = getSingleStringParamValue(aRenderer, false);
        if(renderer.equals(aH8Common)) 
          picture = "picture";
        else if(renderer.equals(aMantra)) 
          picture = "vm_picture";
        else if(renderer.equals(aMentalRay)) 
          picture = "mi_filename0";
        else if(renderer.equals(aRenderMan)) 
          picture = "ri_display";
        else 
          throw new PipelineException("Unknown " + aRenderer + " type (" + renderer + ")!");
      }

      if(targetSeq.hasFrameNumbers()) {
	FilePattern fpat = targetSeq.getFilePattern();
	FrameRange frange = targetSeq.getFrameRange();
	out.write("opparm " + opname + " trange on\n" +
		  "opparm " + opname + " f1 " + frange.getStart() + "\n" +
		  "opparm " + opname + " f2 " + frange.getEnd() + "\n" +
		  "opparm " + opname + " f3 " + frange.getBy() + "\n" +
		  "opparm " + opname + " " + picture + " '" + fpat.getPrefix() + ".$F");

	if(fpat.getPadding() > 1) 
	  out.write(String.valueOf(fpat.getPadding()));
	
	out.write("." + fpat.getSuffix() + "'\n");
      }
      else {
	out.write("opparm " + opname + " trange off\n" +
		  "opparm " + opname + " " + picture + " '" + targetSeq + "'\n");
      }

      writePreRenderScriptOpparm(opname, agenda, out); 
      writePostRenderScriptOpparm(opname, agenda, out); 
      writePreFrameScriptOpparm(opname, agenda, out); 
      writePostFrameScriptOpparm(opname, agenda, out); 

      out.write("opparm -c " + opname + " execute\n" + 
                "quit\n");

      out.close();
    }
    catch(IOException ex) {
      throw new PipelineException
	("Unable to write temporary script file (" + hscript + ") for Job " + 
	 "(" + agenda.getJobID() + ")!\n" +
	 ex.getMessage());
    }

    /* create the process to run the action */ 
    {
      String program = "hscript";
      if((hvid != null) && (hvid.compareTo(new VersionID("8.1.0")) >= 0))
        program = "hbatch";

      ArrayList<String> args = new ArrayList<String>(); 
      if(!getSingleBooleanParamValue(aUseGraphicalLicense)) 
        args.add("-R"); 
      args.add("-i"); 
      args.add("-v"); 
      args.addAll(getExtraOptionsArgs()); 
      args.add(source.toOsString());
      args.add(hscript.toOsString());

      return createSubProcess(agenda, program, args, outFile, errFile);
    }
  }
    


  /*----------------------------------------------------------------------------------------*/
  /*   S T A T I C   I N T E R N A L S                                                      */
  /*----------------------------------------------------------------------------------------*/

  private static final long serialVersionUID = -1664892126861829266L;

  public static final String aRenderer  = "Renderer"; 
  public static final String aH8Common  = "H8 Common"; 
  public static final String aMantra    = "Mantra"; 
  public static final String aMentalRay = "MentalRay"; 
  public static final String aRenderMan = "RenderMan"; 

}

