/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_temerity_pipeline_NativeProcessStats */

#ifndef _Included_us_temerity_pipeline_NativeProcessStats
#define _Included_us_temerity_pipeline_NativeProcessStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_temerity_pipeline_NativeProcessStats
 * Method:    collectStatsNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_us_temerity_pipeline_NativeProcessStats_collectStatsNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
