/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_temerity_pipeline_NativeOS */

#ifndef _Included_us_temerity_pipeline_NativeOS
#define _Included_us_temerity_pipeline_NativeOS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_temerity_pipeline_NativeOS
 * Method:    nativeGetTotalMemoryNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_us_temerity_pipeline_NativeOS_getTotalMemoryNative
  (JNIEnv *, jclass);

/*
 * Class:     us_temerity_pipeline_NativeOS
 * Method:    getNumProcessorsNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_NativeOS_getNumProcessorsNative
  (JNIEnv *, jclass);

/*
 * Class:     us_temerity_pipeline_NativeOS
 * Method:    getLoadAverageNative
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_us_temerity_pipeline_NativeOS_getLoadAverageNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
