/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_temerity_pipeline_NativeProcessLight */

#ifndef _Included_us_temerity_pipeline_NativeProcessLight
#define _Included_us_temerity_pipeline_NativeProcessLight
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    writeToStdIn
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_NativeProcessLight_writeToStdIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    closeStdIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_NativeProcessLight_closeStdIn
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    readFromStdOut
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_us_temerity_pipeline_NativeProcessLight_readFromStdOut
  (JNIEnv *, jobject, jint);

/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    closeStdOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_NativeProcessLight_closeStdOut
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    readFromStdErr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_us_temerity_pipeline_NativeProcessLight_readFromStdErr
  (JNIEnv *, jobject, jint);

/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    closeStdErr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_NativeProcessLight_closeStdErr
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    signalNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_NativeProcessLight_signalNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     us_temerity_pipeline_NativeProcessLight
 * Method:    execNativeLight
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_NativeProcessLight_execNativeLight
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
