/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_temerity_pipeline_NativeFileStat */

#ifndef _Included_us_temerity_pipeline_NativeFileStat
#define _Included_us_temerity_pipeline_NativeFileStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_temerity_pipeline_NativeFileStat
 * Method:    statNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_NativeFileStat_statNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
