/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_temerity_pipeline_core_DNotify */

#ifndef _Included_us_temerity_pipeline_core_DNotify
#define _Included_us_temerity_pipeline_core_DNotify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_temerity_pipeline_core_DNotify
 * Method:    initNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_core_DNotify_initNative
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_core_DNotify
 * Method:    monitorNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_core_DNotify_monitorNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     us_temerity_pipeline_core_DNotify
 * Method:    unmonitorNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_core_DNotify_unmonitorNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     us_temerity_pipeline_core_DNotify
 * Method:    watchNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_core_DNotify_watchNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
