/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_temerity_pipeline_core_NativeProcess */

#ifndef _Included_us_temerity_pipeline_core_NativeProcess
#define _Included_us_temerity_pipeline_core_NativeProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    writeToStdIn
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_core_NativeProcess_writeToStdIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    closeStdIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_core_NativeProcess_closeStdIn
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    readFromStdOut
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_us_temerity_pipeline_core_NativeProcess_readFromStdOut
  (JNIEnv *, jobject, jint);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    closeStdOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_core_NativeProcess_closeStdOut
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    readFromStdErr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_us_temerity_pipeline_core_NativeProcess_readFromStdErr
  (JNIEnv *, jobject, jint);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    closeStdErr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_core_NativeProcess_closeStdErr
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    execNative
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_us_temerity_pipeline_core_NativeProcess_execNative
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jstring);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    collectStatsNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_us_temerity_pipeline_core_NativeProcess_collectStatsNative
  (JNIEnv *, jobject);

/*
 * Class:     us_temerity_pipeline_core_NativeProcess
 * Method:    signalNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_us_temerity_pipeline_core_NativeProcess_signalNative
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
