/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeProcess */

#ifndef _Included_pipeline_NativeProcess
#define _Included_pipeline_NativeProcess
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
#undef NativeProcess_SIGHUP
#define NativeProcess_SIGHUP 1L
#undef NativeProcess_SIGINT
#define NativeProcess_SIGINT 2L
#undef NativeProcess_SIGQUIT
#define NativeProcess_SIGQUIT 3L
#undef NativeProcess_SIGILL
#define NativeProcess_SIGILL 4L
#undef NativeProcess_SIGABRT
#define NativeProcess_SIGABRT 6L
#undef NativeProcess_SIGFPE
#define NativeProcess_SIGFPE 8L
#undef NativeProcess_SIGKILL
#define NativeProcess_SIGKILL 9L
#undef NativeProcess_SIGSEGV
#define NativeProcess_SIGSEGV 11L
#undef NativeProcess_SIGPIPE
#define NativeProcess_SIGPIPE 13L
#undef NativeProcess_SIGALRM
#define NativeProcess_SIGALRM 14L
#undef NativeProcess_SIGTERM
#define NativeProcess_SIGTERM 15L
#undef NativeProcess_SIGUSR1
#define NativeProcess_SIGUSR1 10L
#undef NativeProcess_SIGUSR2
#define NativeProcess_SIGUSR2 12L
#undef NativeProcess_SIGCHLD
#define NativeProcess_SIGCHLD 17L
#undef NativeProcess_SIGCONT
#define NativeProcess_SIGCONT 18L
#undef NativeProcess_SIGSTOP
#define NativeProcess_SIGSTOP 19L
#undef NativeProcess_SIGTSTP
#define NativeProcess_SIGTSTP 20L
#undef NativeProcess_SIGTTIN
#define NativeProcess_SIGTTIN 21L
#undef NativeProcess_SIGTTOU
#define NativeProcess_SIGTTOU 22L
/* Inaccessible static: class_00024pipeline_00024NativeProcess */
/*
 * Class:     NativeProcess
 * Method:    writeToStdIn
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pipeline_NativeProcess_writeToStdIn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeProcess
 * Method:    closeStdIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pipeline_NativeProcess_closeStdIn
  (JNIEnv *, jobject);

/*
 * Class:     NativeProcess
 * Method:    readFromStdOut
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pipeline_NativeProcess_readFromStdOut
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeProcess
 * Method:    closeStdOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pipeline_NativeProcess_closeStdOut
  (JNIEnv *, jobject);

/*
 * Class:     NativeProcess
 * Method:    readFromStdErr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pipeline_NativeProcess_readFromStdErr
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeProcess
 * Method:    closeStdErr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pipeline_NativeProcess_closeStdErr
  (JNIEnv *, jobject);

/*
 * Class:     NativeProcess
 * Method:    execNative
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_pipeline_NativeProcess_execNative
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jstring);

/*
 * Class:     NativeProcess
 * Method:    collectStatsNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_pipeline_NativeProcess_collectStatsNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     NativeProcess
 * Method:    killNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pipeline_NativeProcess_killNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
