#!/bin/bash

for studio in `find . -maxdepth 1 -name "??*" -type d`
do
  echo
  echo "===================================================================================="
  echo "  "$studio
  echo "===================================================================================="
  echo
  pushd $studio
  ./make-local $*
  popd 
done
