#!/bin/bash

JAR=$1
srcdir=$2

rm -f plugin-all

for pdir in `find . -mindepth 1 -maxdepth 1 -type d | sort`
do 
  plugin=`echo $pdir | awk -F/ '{print $2}'`

  for vdir in `find $pdir -mindepth 1 -maxdepth 1 -type d | sort`
  do 
    version=`echo $vdir | awk -F/ '{print $3}'`
#   echo $plugin $version

    cnt=`find $vdir -type f -name "*.class" | wc -l`

    #
    # For the Temerity plugins all the resources for the plugin go in a directory named 
    # RESOURCES.  The resources should be placed in the directory as if it was relative to the plugin class file.
    # This script will take care of putting the resources in the jar in the proper directories.
    #
    rcnt=`find $srcdir/us/temerity/pipeline/plugin/$plugin/$version/ -type f | grep -v \/CVS\/ | grep RESOURCES | wc -l`

    if [ $cnt -eq 1 -a $rcnt -eq 0 ] 
    then
      cfile=`find $vdir -type f -name "*.class" | sed 's:\./:us/temerity/pipeline/plugin/:g'`
      echo "PLUGIN CLASS:" $cfile
      echo $cfile >> plugin-all
    else 
      jfile=us/temerity/pipeline/plugin/$plugin/$version/$plugin.jar
      echo "PLUGIN JAR:" $jfile
      pushd ../../../.. >& /dev/null
        echo $JAR cvf $jfile \
          `find us/temerity/pipeline/plugin/$plugin/$version -type f -name "*.class"`
        $JAR cvf $jfile \
          `find us/temerity/pipeline/plugin/$plugin/$version -type f -name "*.class"`
      popd >& /dev/null
      echo $jfile >> plugin-all

      #
      # Add the resources to the jar file from the RESOURCES directory.  First create the 
      # intermediate directories in a temporary directory.  Then copy the files from the RESOURCES 
      # directory into the temporary directory and add to the jar.
      #
      if [ $rcnt -gt 0 ]
      then
	rm -rf $plugin/$version/TMP-RESOURCES
	mkdir -p $plugin/$version/TMP-RESOURCES/us/temerity/pipeline/plugin/$plugin/$version/
	cp -R $srcdir/us/temerity/pipeline/plugin/$plugin/$version/RESOURCES/* $plugin/$version/TMP-RESOURCES/us/temerity/pipeline/plugin/$plugin/$version/
	pushd $plugin/$version/TMP-RESOURCES >& /dev/null
	  $JAR uvf ../$plugin.jar `find . -type f | grep -v \/CVS\/`
	popd >& /dev/null
	rm -rf $plugin/$version/TMP-RESOURCES
      fi
    fi
  done
done

