package us.temerity.pipeline.plugin.MayaCurvesExportAction.v2_3_4;

import java.io.*;

import us.temerity.pipeline.*;
import us.temerity.pipeline.plugin.MayaActionUtils;

/*------------------------------------------------------------------------------------------*/
/*   M A Y A   C U R V E S   E X P O R T   A C T I O N                                      */
/*------------------------------------------------------------------------------------------*/
/**
 * Action that exports animation data as animation curves from a maya scene.
 * <p>
 * This action defines the following single valued parameters: <BR>
 * 
 * <DIV style="margin-left: 40px;">
 *   Maya Scene <BR>
 *   <DIV style="margin-left: 40px;">
 *     The Maya scene containing the shaders to be exported.
 *   </DIV> <BR>
 *     
 *   Export Set<BR>
 *   <DIV style="margin-left: 40px;">
 *     The name of the Maya Set used to identify the DAG nodes whose animation 
 *     channels should be exported. 
 *   </DIV> <BR>
 *     
 *   Bake Animation <BR>
 *   <DIV style="margin-left: 40px;">
 *     Should the animation be baked before it is exported.
 *   </DIV> <BR>
 *   
 *   Selected Time Range<BR>
 *   <DIV style="margin-left: 40px;">
 *     Should the animation only be baked over the time range of the selected objects before it
  	   is exported.  If this is set to (no), then it will be baked over a frame range for
  	   everything in the scene.
 *   </DIV> <BR>
 *   
 *   Alternative Bake MEL<BR>
 *   <DIV style="margin-left: 40px;">
 *     An alternative MEL snippet to do the animation baking.  This code will be
 *     inserted directly into the MEL script generated by this Action.  The variable
 *     $export exists in the script and contains the name of the set being used to
 *     export the animation.  The value of $export should not be changed.
 *   </DIV> <BR>     

 *     
 *   Clean Up Namespace <BR>
 *   <DIV style="margin-left: 40px;">
 *     Do we need to run a MEL script to clean up namespaces after the export.
 *   </DIV> <BR>
 *   
 *   Initial MEL <BR>
 *   <DIV style="margin-left: 40px;">
 *     The source node containing the MEL script to evaluate just after the scene is 
 *     opened.
 *   </DIV> <BR>
 * 
 *   Final MEL <BR>
 *   <DIV style="margin-left: 40px;">
 *     The source node containing the MEL script to evaluate after saving the generated 
 *     Maya scene.
 *   </DIV> <BR>
 *   
 *   New Scene MEL <BR>
 *   <DIV style="margin-left: 40px;">
 *     A MEL script to evaluate in the scene created by exporting the animation.
 *   </DIV>    
 * </DIV>  
 */
public 
class MayaCurvesExportAction
  extends MayaActionUtils
{
  /*----------------------------------------------------------------------------------------*/
  /*   C O N S T R U C T O R                                                                */
  /*----------------------------------------------------------------------------------------*/
  
public
  MayaCurvesExportAction()
  {
    super("MayaCurvesExport", new VersionID("2.3.4"), "Temerity",
      "An Action to export animation curves from an animated scene.");
    
    {
      ActionParam param = 
	new LinkActionParam
	(aMayaScene, 
	 "The Maya scene containing the target for the animation.", 
	 null); 
      addSingleParam(param);
    }

    {
      ActionParam param = 
	new StringActionParam
	(aExportSet, 
	 "The name of the Maya Set used to identify the DAG nodes " +
	 "whose animation channels should be exported.", 
	 "SELECT"); 
      addSingleParam(param);
    }
    
    {
      ActionParam param = 
	new BooleanActionParam
	(aBakeAnimation,
	 "Should the animation be baked before it is exported.", 
	 false); 
      addSingleParam(param);
    }
    
    {
        ActionParam param = 
  	new BooleanActionParam
  	(aSelectedTimeRange,
  	 "Should the animation only be baked over the time range of the selected objects " + 
         "before it is exported.  If this is set to (no), then it will be baked over a " + 
         "frame range for everything in the scene.", 
  	 false); 
        addSingleParam(param);
      }

    
    {
      ActionParam param = 
	new LinkActionParam
	(aAlternativeBakeMEL,
	 "An alternative MEL snippet to do the animation baking.  This code will be " +
	 "inserted directly into the MEL script generated by this Action.  The variable " +
	 "$export exists in the script and contains the name of the set being used to " +
	 "export the animation.  The value of $export should not be changed.", 
	 null); 
      addSingleParam(param);
    }
    
    {
      ActionParam param = 
	new BooleanActionParam
	(aCleanUpNamespace,
	 "Do we need to run a MEL script to clean up namespaces after the export.  " +
	 "This will be ignored if the Namespace param is null.", 
	 false); 
      addSingleParam(param);
    }
    
    {
      ActionParam param = 
	new LinkActionParam
	(aNewSceneMEL,
	 "A MEL script to evaluate in the scene created by exporting the animation.", 
	 null); 
      addSingleParam(param);
    }
    
    addInitalMELParam();
    addFinalMELParam();
    
    {
      LayoutGroup layout = new LayoutGroup(true);
      layout.addEntry(aMayaScene);
      layout.addEntry(aExportSet);
      layout.addEntry(aCleanUpNamespace);
      layout.addSeparator();
      layout.addEntry(aBakeAnimation);
      layout.addEntry(aSelectedTimeRange);
      layout.addEntry(aAlternativeBakeMEL);
      layout.addSeparator();
      layout.addEntry(aInitialMEL);
      layout.addEntry(aFinalMEL);
      layout.addEntry(aNewSceneMEL);
      
      setSingleLayout(layout);
    }
    
    addSupport(OsType.Windows);
    addSupport(OsType.MacOS);
  }



  /*----------------------------------------------------------------------------------------*/
  /*   A C T I O N                                                                          */
  /*----------------------------------------------------------------------------------------*/

  /**
   * Construct a {@link SubProcessHeavy SubProcessHeavy} instance which when executed will 
   * fulfill the given action agenda. <P> 
   * 
   * @param agenda
   *   The agenda to be accomplished by the action.
   * 
   * @param outFile 
   *   The file to which all STDOUT output is redirected.
   * 
   * @param errFile 
   *   The file to which all STDERR output is redirected.
   * 
   * @return 
   *   The SubProcess which will fulfill the agenda.
   * 
   * @throws PipelineException 
   *   If unable to prepare a SubProcess due to illegal, missing or imcompatable 
   *   information in the action agenda or a general failure of the prep method code.
   */
  public SubProcessHeavy
  prep
  (
   ActionAgenda agenda,
   File outFile, 
   File errFile 
  )
    throws PipelineException
  { 
    /* the target Maya scene containing the exported shaders */
    Path targetScene = getMayaSceneTargetPath(agenda);
    String sceneType = getMayaSceneType(agenda);
    String suffix = agenda.getPrimaryTarget().getFilePattern().getSuffix();
    
    /* the source Maya scene */ 
    Path mayaSourceScene = getMayaSceneSourcePath(aMayaScene, agenda);
    
    /* the mel script path*/
    Path newSceneMEL = getMelScriptSourcePath(aNewSceneMEL, agenda);
    Path bakeMEL = getMelScriptSourcePath(aAlternativeBakeMEL, agenda);
    
    boolean bakeAnim = getSingleBooleanParamValue(aBakeAnimation);
    boolean selectedTime = getSingleBooleanParamValue(aSelectedTimeRange);
    
    boolean cleanUp = getSingleBooleanParamValue(aCleanUpNamespace);
    boolean tempScene = false;
    if ( (newSceneMEL != null) || cleanUp )
      tempScene = true;
    
    Path newScene = null;
    if (tempScene)
      newScene = new Path(getTempPath(agenda), "tempMayaScene." + suffix); 
    
    String exportSet = getSingleStringParamValue(aExportSet);
    
    /* create a temporary MEL script used to export the curves*/ 
    File script = createTemp(agenda, "mel");
    try {
      FileWriter out = new FileWriter(script);

      writeInitialMEL(agenda, out);
      
      
      out.write("string $export = \"" + exportSet + "\";\n");
      if (bakeAnim)
	if (bakeMEL == null) {
	  out.write("select -r $export;\n");
	  if (selectedTime)
	  out.write("//Baking over selected frame range\n" +
	  		"selectKey -time \":\" `ls -sl`;\n" + 
	  	    "float $first = `findKeyframe -w \"first\"`;\n" + 
	  	    "float $last = `findKeyframe -w \"last\"`;\n");
	  else
		  out.write("//Baking over whole frame range\n" +
		  		"selectKey -time \":\" `ls`;\n" + 
			  	    "float $first = `findKeyframe -w \"first\"`;\n" + 
			  	    "float $last = `findKeyframe -w \"last\"`;\n");
	  out.write
	    ("if ($first != $last)\n" + 
	  	 "{\n" +
	  	 "  select -r $export;\n" +
	  	 "  if (size(`ls -sl`) > 0)\n" +
	  	 "    bakeResults -t ($first + \":\" + $last) -simulation true `ls -sl`;\n" +
	     "}\n\n");
	}
	else {
	  String melSnippet = null;
	  try {
	    melSnippet = getMelSnippet(agenda);
	  }
	  catch (IOException ex) {
	    throw new PipelineException
	    ("Unable to read the export mod mel file for Job " + 
	     "(" + agenda.getJobID() + ")!\n" +
	     ex.getMessage());
	  }
	  if (melSnippet != null) {
	    out.write(melSnippet);
	  }
	}
      
      out.write("select -r $export;\n");
      
      Path actualTarget = targetScene;
      if (tempScene)
	actualTarget = newScene;
      
      out.write
        ("if (catch(`file -f " +
      	 "-type \"" + sceneType + "\" " +
      	 "-eas \"" + actualTarget + "\"`))\n" +
      	 "{\n" + 
      	 "  file -new;\n" + 
      	 "  file -rename \"" + actualTarget + "\";\n" + 
      	 "  file -type \"" + sceneType + "\";\n" + 
      	 "  file -save;\n" +
         "}\n"); 

      
      writeFinalMEL(agenda, out);
      
      if (tempScene) {
	out.write("// NEW SCENE SCRIPT\n" +
	          "file -open -f \"" + newScene + "\";\n");
	if (cleanUp)
	  out.write("string $ns;\n" + 
	  	    "for ($ns in `namespaceInfo -lon`) {\n" + 
	  	    "  if ($ns != \"UI\")\n" + 
	  	    "    catch(`namespace -f -mv $ns \":\"`);\n" + 
	            "}\n\n");
	if (newSceneMEL != null)
	  out.write("print \"New-Scene Script: " + newSceneMEL+ "\\n\";\n" +
	  	    "source \"" + newSceneMEL + "\";\n");
	out.write("file -rename \"" + targetScene + "\";\n" + 
		  "file -save\n;");
      }
      
      out.write("print \"ALL DONE.\\n\";\n");
      
      out.close();
    } 
    catch (IOException ex) {
      throw new PipelineException
	("Unable to write temporary MEL script file (" + script + ") for Job " + 
	 "(" + agenda.getJobID() + ")!\n" +
	 ex.getMessage());
    }
    
    /* create the process to run the action */
    return createMayaSubProcess(mayaSourceScene, script, true, agenda, outFile, errFile);
  }

  
  
  private String 
  getMelSnippet
  (
    ActionAgenda agenda  
  )
    throws PipelineException, IOException
  {
    String toReturn = null;
    Path melPath = getMelScriptSourcePath(aAlternativeBakeMEL, agenda);
    if (melPath == null)
      return toReturn;
    File file = melPath.toFile();
    BufferedReader in = new BufferedReader(new FileReader(file));
    while(true) {
      String line = in.readLine();
      if(line == null) 
        break;
      if (toReturn == null)
	toReturn = line + "\n";
      else
	toReturn += line + "\n";
    }
    return toReturn;
  }
  
  
  
  /*----------------------------------------------------------------------------------------*/
  /*   S T A T I C   I N T E R N A L S                                                      */
  /*----------------------------------------------------------------------------------------*/
  
  public static final String aExportSet          = "ExportSet";
  public static final String aNewSceneMEL        = "NewSceneMEL";
  public static final String aCleanUpNamespace   = "CleanUpNamespace";
  public static final String aBakeAnimation      = "BakeAnimation";
  public static final String aSelectedTimeRange  = "SelectedTimeRange";
  public static final String aAlternativeBakeMEL = "AlternativeBakeMEL";
 
	private static final long serialVersionUID = -5925015626788085391L;

}
