// $Id: NodeGetEventsReq.java,v 1.1 2007/01/01 16:09:51 jim Exp $

package us.temerity.pipeline.message;

import us.temerity.pipeline.*; 
import us.temerity.pipeline.core.*; 

import java.io.*;
import java.util.*;

/*------------------------------------------------------------------------------------------*/
/*   N O D E   G E T   E V E N T S   R E Q                                                  */
/*------------------------------------------------------------------------------------------*/

/**
 * Retrieve the record of all significant operations involving the given nodes during
 * the specified time interval.
 */
public
class NodeGetEventsReq
  implements Serializable
{
  /*----------------------------------------------------------------------------------------*/
  /*   C O N S T R U C T O R S                                                              */
  /*----------------------------------------------------------------------------------------*/

  /** 
   * Constructs a new request. <P> 
   * 
   * @param names 
   *   Limit the events to those associated with the given fully resolved node names or
   *   <CODE>null</CODE> for all nodes.
   * 
   * @param users
   *   Limit the events to those generated by the given user names or
   *   <CODE>null</CODE> for all users.
   * 
   * @param interval
   *   Limit the events to those which occured within the given time interval or 
   *   <CODE>null</CODE> for all times.
   */
  public
  NodeGetEventsReq
  (
   TreeSet<String> names, 
   TreeSet<String> users, 
   DateInterval interval   
  )
  { 
    super();

    pNames    = names;
    pUsers    = users; 
    pInterval = interval;
  }



  /*----------------------------------------------------------------------------------------*/
  /*   A C C E S S                                                                          */
  /*----------------------------------------------------------------------------------------*/

  /**
   * Limit events to those associated with the given fully resolved node names or
   * <CODE>null</CODE> for all nodes.
   */
  public TreeSet<String>
  getNames() 
  {
    return pNames; 
  }

  /**
   * Limit the events to those generated by the given user names or
   * <CODE>null</CODE> for all users.
   */
  public TreeSet<String>
  getUsers() 
  {
    return pUsers; 
  }

  /**
   * Limit the events to those which occured within the given time interval or 
   * <CODE>null</CODE> for all times.
   */ 
  public DateInterval
  getInterval() 
  {
    return pInterval; 
  }

  

  /*----------------------------------------------------------------------------------------*/
  /*   S T A T I C   I N T E R N A L S                                                      */
  /*----------------------------------------------------------------------------------------*/

  private static final long serialVersionUID = -1112698332043318859L;

  

  /*----------------------------------------------------------------------------------------*/
  /*   I N T E R N A L S                                                                    */
  /*----------------------------------------------------------------------------------------*/

  /**
   * Limit events to those associated with the given fully resolved node names or
   * <CODE>null</CODE> for all nodes.
   */ 
  private TreeSet<String>  pNames; 

  /**
   * Limit the events to those generated by the given user names or
   * <CODE>null</CODE> for all users.
   */ 
  private TreeSet<String>  pUsers; 

  /**
   * Limit the events to those which occured within the given time interval or 
   * <CODE>null</CODE> for all times.
   */ 
  private DateInterval  pInterval; 

}
  
