#--- RULES -----------------------------------------------------------------------------------

%: 
	$(MAKE) -f Makefile.local -C v1_0_0 $@ 
	$(MAKE) -f Makefile.local -C v1_1_0 $@ 
	$(MAKE) -f Makefile.local -C v1_2_0 $@ 
	$(MAKE) -f Makefile.local -C v1_3_0 $@
