Summary: Java3D 
Name: java3d_sdk
Version: 1.1.1
Release: 01
Copyright: public domain
Group: Development/Libraries
Requires: libc.so.6 
Requires: libc.so.6(GLIBC_2.0) 
Requires: libdl.so.2 
Requires: libGL.so.1 
Requires: libm.so.6 
Requires: libnsl.so.1 
Requires: libpthread.so.0 
Requires: libpthread.so.0(GLIBC_2.0) 
Requires: libX11.so.6 
Requires: libXext.so.6
Source0: java3d-sdk-1.3-fcs-linux-i386.bin
BuildRoot: %{_tmppath}/%{name}-%{version}-root
URL: http://java.sun.com/products/java-media/3D/download.html
Packager: Jim Callahan <jim@polaris.net>

%define __find_requires %{null}

%description

The Java 3D API enables the creation of three-dimensional graphics applications 
and Internet-based 3D applets. It provides high-level constructs for creating and 
manipulation 3D geometry and building the structures used in rendering that 
geometry. With this software, you can efficiently define and render very large 
virtual worlds. 

%prep

%build


%install
mkdir -p $RPM_BUILD_ROOT/usr/java/j2sdk1.4.2

cd $RPM_BUILD_ROOT/usr/java/j2sdk1.4.2
env MORE=true sh /usr/src/redhat/SOURCES/java3d-sdk-1.3-fcs-linux-i386.bin <<EOF
yes
EOF


%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root)
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceBoundsTest.class
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceBoundsTest.java
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceScopeTest.class
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceScopeTest.java
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/SphereGroup.class
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/SphereGroup.java
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceBoundsTest.html
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceBoundsTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceScopeTest.html
/usr/java/j2sdk1.4.2/demo/java3d/AlternateAppearance/AlternateAppearanceScopeTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Appearance/AppearanceTest.java
/usr/java/j2sdk1.4.2/demo/java3d/Appearance/AppearanceTest.class
/usr/java/j2sdk1.4.2/demo/java3d/Appearance/Tetrahedron.java
/usr/java/j2sdk1.4.2/demo/java3d/Appearance/Tetrahedron.class
/usr/java/j2sdk1.4.2/demo/java3d/Appearance/AppearanceTest.html
/usr/java/j2sdk1.4.2/demo/java3d/Appearance/AppearanceTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/AppearanceMixed/AppearanceMixed.java
/usr/java/j2sdk1.4.2/demo/java3d/AppearanceMixed/AppearanceMixed.class
/usr/java/j2sdk1.4.2/demo/java3d/AppearanceMixed/AppearanceMixed$MyCanvas3D.class
/usr/java/j2sdk1.4.2/demo/java3d/AppearanceMixed/Tetrahedron.java
/usr/java/j2sdk1.4.2/demo/java3d/AppearanceMixed/Tetrahedron.class
/usr/java/j2sdk1.4.2/demo/java3d/AppearanceMixed/AppearanceMixed.html
/usr/java/j2sdk1.4.2/demo/java3d/AppearanceMixed/AppearanceMixed_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/AWT_Interaction/AWTInteraction.java
/usr/java/j2sdk1.4.2/demo/java3d/AWT_Interaction/AWTInteraction.class
/usr/java/j2sdk1.4.2/demo/java3d/AWT_Interaction/AWTInteraction.html
/usr/java/j2sdk1.4.2/demo/java3d/AWT_Interaction/AWTInteraction_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/AWT_Interaction/AWTInteractionBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/AWT_Interaction/AWTInteractionBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/Background/BackgroundGeometry.java
/usr/java/j2sdk1.4.2/demo/java3d/Background/BackgroundGeometry.class
/usr/java/j2sdk1.4.2/demo/java3d/Background/BackgroundGeometry.html
/usr/java/j2sdk1.4.2/demo/java3d/Background/BackgroundGeometry_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/README.txt
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/ConfigObjLoad.class
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/ConfigObjLoad$1$QuitListener.class
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/ConfigObjLoad.java
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x1
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x1-behavior
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x1-stereo
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x1-vr
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x1-window
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x2-flat
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x2-rot30
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x3-cave
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x3-cave-vr
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d1x3-rot45
/usr/java/j2sdk1.4.2/demo/java3d/ConfiguredUniverse/j3d2x2-flat
/usr/java/j2sdk1.4.2/demo/java3d/ConicWorld/ConicWorld.java
/usr/java/j2sdk1.4.2/demo/java3d/ConicWorld/ConicWorld.class
/usr/java/j2sdk1.4.2/demo/java3d/ConicWorld/ConicWorld.html
/usr/java/j2sdk1.4.2/demo/java3d/ConicWorld/ConicWorld_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/FPSCounter/FPSCounter.class
/usr/java/j2sdk1.4.2/demo/java3d/FPSCounter/FPSCounter.java
/usr/java/j2sdk1.4.2/demo/java3d/FPSCounter/FPSCounterDemo.class
/usr/java/j2sdk1.4.2/demo/java3d/FPSCounter/FPSCounterDemo.html
/usr/java/j2sdk1.4.2/demo/java3d/FPSCounter/FPSCounterDemo.java
/usr/java/j2sdk1.4.2/demo/java3d/FPSCounter/FPSCounterDemo_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/BigCube.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/BigCube.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Board.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Board.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Canvas2D.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Canvas2D.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Cube.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Cube.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Cylinder.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Cylinder.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/FourByFour.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/FourByFour.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/FourByFour$killAdapter.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/ID.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/ID.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/PickDragBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/PickDragBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Poles.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Poles.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Positions.java
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/Positions.class
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/README
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/FourByFour.html
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/FourByFour_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/instructions.txt
/usr/java/j2sdk1.4.2/demo/java3d/FourByFour/scores.txt
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/Gear.java
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/Gear.class
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearBox.java
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearBox.class
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearTest.java
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearTest.class
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/Shaft.java
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/Shaft.class
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/SpurGear.java
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/SpurGear.class
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/SpurGearThinBody.java
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/SpurGearThinBody.class
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearBox.html
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearBox_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearTest.html
/usr/java/j2sdk1.4.2/demo/java3d/GearTest/GearTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/GeometryByReferenceTest.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/GeometryByReferenceTest.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/InterleavedTest.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/InterleavedTest.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/ImageComponentByReferenceTest.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/ImageComponentByReferenceTest.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/TiledImage.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/TiledImage.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/GeometryByReferenceTest.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/GeometryByReferenceTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/ImageComponentByReferenceTest.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/ImageComponentByReferenceTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/InterleavedTest.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/InterleavedTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/GeometryByReferenceNIOBuffer.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/GeometryByReferenceNIOBuffer.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/InterleavedNIOBuffer.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryByReference/InterleavedNIOBuffer.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/README
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/ObjectFileCompressor.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/ObjectFileCompressor.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/ObjectFileCompressor.html
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/cgview.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/cgview.java
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/obj2cg.class
/usr/java/j2sdk1.4.2/demo/java3d/GeometryCompression/obj2cg.java
/usr/java/j2sdk1.4.2/demo/java3d/HelloUniverse/HelloUniverse.html
/usr/java/j2sdk1.4.2/demo/java3d/HelloUniverse/HelloUniverse_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/HelloUniverse/HelloUniverse.java
/usr/java/j2sdk1.4.2/demo/java3d/HelloUniverse/HelloUniverse.class
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/README.txt
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/Viewer.java
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/Viewer.class
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/ballcone.lws
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/greenball.lwo
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/redcone.lwo
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/Viewer.html
/usr/java/j2sdk1.4.2/demo/java3d/Lightwave/Viewer_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/LOD/LOD.class
/usr/java/j2sdk1.4.2/demo/java3d/LOD/LOD.java
/usr/java/j2sdk1.4.2/demo/java3d/LOD/LOD.html
/usr/java/j2sdk1.4.2/demo/java3d/LOD/LOD_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest.java
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest.class
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest2.java
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest2.class
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest.html
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest2.html
/usr/java/j2sdk1.4.2/demo/java3d/ModelClip/ModelClipTest2_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/ColorCube.java
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/ColorCube.class
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/ColorPyramidDown.java
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/ColorPyramidDown.class
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/ColorPyramidUp.java
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/ColorPyramidUp.class
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Morphing.java
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Morphing.class
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/MorphingBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/MorphingBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Pyramid2Cube.java
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Pyramid2Cube.class
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/hand1.obj
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/hand2.obj
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/hand3.obj
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Morphing.html
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Morphing_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Pyramid2Cube.html
/usr/java/j2sdk1.4.2/demo/java3d/Morphing/Pyramid2Cube_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/ObjLoad/ObjLoad.java
/usr/java/j2sdk1.4.2/demo/java3d/ObjLoad/ObjLoad.class
/usr/java/j2sdk1.4.2/demo/java3d/ObjLoad/ObjLoad.html
/usr/java/j2sdk1.4.2/demo/java3d/ObjLoad/ObjLoad_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/ObjLoad/galleon.obj
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OffScreenCanvas3D.java
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OffScreenCanvas3D.class
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OffScreenTest.java
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OffScreenTest.class
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OnScreenCanvas3D.java
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OnScreenCanvas3D.class
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/PrintFromButton.java
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/PrintFromButton.class
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OffScreenTest.html
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/OffScreenTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/PrintFromButton.html
/usr/java/j2sdk1.4.2/demo/java3d/OffScreenCanvas3D/PrintFromButton_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedPtTest.java
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedPtTest.class
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedTest.java
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedTest.class
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/MouseRotateY.java
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/MouseRotateY.class
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedTest.html
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedPtTest.html
/usr/java/j2sdk1.4.2/demo/java3d/OrientedShape3D/OrientedPtTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PackageInfo/PackageInfo.java
/usr/java/j2sdk1.4.2/demo/java3d/PackageInfo/PackageInfo.class
/usr/java/j2sdk1.4.2/demo/java3d/PackageInfo/QueryProperties.java
/usr/java/j2sdk1.4.2/demo/java3d/PackageInfo/QueryProperties.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/BoltCG.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/BoltCG.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/ColorCube.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/ColorCube.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/ColorPyramidDown.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/ColorPyramidDown.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/ColorPyramidUp.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/ColorPyramidUp.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/CubeIQA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/CubeIQA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/CubeQA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/CubeQA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/GullCG.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/GullCG.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IcosahedronITSA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IcosahedronITSA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IcosahedronTSA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IcosahedronTSA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IntersectInfoBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IntersectInfoBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IntersectTest.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IntersectTest.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/MorphingBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/MorphingBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/OctahedronITFA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/OctahedronITFA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/OctahedronTFA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/OctahedronTFA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/PickTest.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/PickTest.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/RandomColorCube.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/RandomColorCube.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/RandomColorTetrahedron.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/RandomColorTetrahedron.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronILA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronILA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronLA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronLA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronILSA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronILSA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronLSA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronLSA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronIPA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronIPA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronPA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronPA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronITA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronITA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronTA.java
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/TetrahedronTA.class
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IntersectTest.html
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/IntersectTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/PickTest.html
/usr/java/j2sdk1.4.2/demo/java3d/PickTest/PickTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DBounds.java
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DBounds.class
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DGeometry.java
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DGeometry.class
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DBounds.html
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DBounds_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DGeometry.html
/usr/java/j2sdk1.4.2/demo/java3d/PickText3D/PickText3DGeometry_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PlatformGeometry/SimpleGeometry.java
/usr/java/j2sdk1.4.2/demo/java3d/PlatformGeometry/SimpleGeometry.class
/usr/java/j2sdk1.4.2/demo/java3d/PlatformGeometry/SimpleGeometry.html
/usr/java/j2sdk1.4.2/demo/java3d/PlatformGeometry/SimpleGeometry_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/ImageDisplayer.java
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/ImagePrinter.java
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/OffScreenCanvas3D.java
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/PrintCanvas3D.java
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/ImageDisplayer$1.class
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/ImageDisplayer$ImagePanel.class
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/ImageDisplayer.class
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/ImagePrinter.class
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/OffScreenCanvas3D.class
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/PrintCanvas3D$1.class
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/PrintCanvas3D$AppPanel.class
/usr/java/j2sdk1.4.2/demo/java3d/PrintCanvas3D/PrintCanvas3D.class
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediate.html
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediate_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediate.java
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediate.class
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediateStereo.html
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediateStereo_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediateStereo.java
/usr/java/j2sdk1.4.2/demo/java3d/PureImmediate/PureImmediateStereo.class
/usr/java/j2sdk1.4.2/demo/java3d/ReadRaster/ReadRaster.java
/usr/java/j2sdk1.4.2/demo/java3d/ReadRaster/ReadRaster.class
/usr/java/j2sdk1.4.2/demo/java3d/ReadRaster/myCanvas3D.class
/usr/java/j2sdk1.4.2/demo/java3d/ReadRaster/myRotationInterpolator.class
/usr/java/j2sdk1.4.2/demo/java3d/ReadRaster/ReadRaster.html
/usr/java/j2sdk1.4.2/demo/java3d/ReadRaster/ReadRaster_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Sound/SimpleSounds.java
/usr/java/j2sdk1.4.2/demo/java3d/Sound/SimpleSounds.class
/usr/java/j2sdk1.4.2/demo/java3d/Sound/MoveAppBoundingLeaf.java
/usr/java/j2sdk1.4.2/demo/java3d/Sound/MoveAppBoundingLeaf.class
/usr/java/j2sdk1.4.2/demo/java3d/Sound/ReverberateSound.java
/usr/java/j2sdk1.4.2/demo/java3d/Sound/ReverberateSound.class
/usr/java/j2sdk1.4.2/demo/java3d/Sound/SimpleSoundsBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/Sound/SimpleSoundsBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/Sound/AudioBehaviorMoveOne.java
/usr/java/j2sdk1.4.2/demo/java3d/Sound/AudioBehaviorMoveOne.class
/usr/java/j2sdk1.4.2/demo/java3d/Sound/AudioReverberate.java
/usr/java/j2sdk1.4.2/demo/java3d/Sound/AudioReverberate.class
/usr/java/j2sdk1.4.2/demo/java3d/Sound/hello_universe.au
/usr/java/j2sdk1.4.2/demo/java3d/Sound/roar.au
/usr/java/j2sdk1.4.2/demo/java3d/Sound/techno_machine.au
/usr/java/j2sdk1.4.2/demo/java3d/Sound/README.release
/usr/java/j2sdk1.4.2/demo/java3d/Sound/SimpleSounds.html
/usr/java/j2sdk1.4.2/demo/java3d/Sound/SimpleSounds_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Sound/MoveAppBoundingLeaf.html
/usr/java/j2sdk1.4.2/demo/java3d/Sound/MoveAppBoundingLeaf_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Sound/ReverberateSound.html
/usr/java/j2sdk1.4.2/demo/java3d/Sound/ReverberateSound_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/SphereMotion/SphereMotion.html
/usr/java/j2sdk1.4.2/demo/java3d/SphereMotion/SphereMotion_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/SphereMotion/SphereMotion.java
/usr/java/j2sdk1.4.2/demo/java3d/SphereMotion/SphereMotion.class
/usr/java/j2sdk1.4.2/demo/java3d/SplineAnim/SplineAnim.java
/usr/java/j2sdk1.4.2/demo/java3d/SplineAnim/SplineAnim.class
/usr/java/j2sdk1.4.2/demo/java3d/SplineAnim/SplineAnim.html
/usr/java/j2sdk1.4.2/demo/java3d/SplineAnim/SplineAnim_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Text2D/MoverBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/Text2D/MoverBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/Text2D/Text2DTest.java
/usr/java/j2sdk1.4.2/demo/java3d/Text2D/Text2DTest.class
/usr/java/j2sdk1.4.2/demo/java3d/Text2D/Text2DTest.html
/usr/java/j2sdk1.4.2/demo/java3d/Text2D/Text2DTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Text3D/Text3DLoad.java
/usr/java/j2sdk1.4.2/demo/java3d/Text3D/Text3DLoad.class
/usr/java/j2sdk1.4.2/demo/java3d/Text3D/Text3DLoad.html
/usr/java/j2sdk1.4.2/demo/java3d/Text3D/Text3DLoad_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/AnimateTexturesBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/AnimateTexturesBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/ImageOps.java
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/ImageOps.class
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/Tetrahedron.java
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/Tetrahedron.class
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/TextureByReference.java
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/TextureByReference.class
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/TextureByReference.html
/usr/java/j2sdk1.4.2/demo/java3d/TextureByReference/TextureByReference_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/TextureImage.java
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/TextureImage.class
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/MultiTextureTest.java
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/MultiTextureTest.class
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/TextureImage.html
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/TextureImage_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/MultiTextureTest.html
/usr/java/j2sdk1.4.2/demo/java3d/TextureTest/MultiTextureTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/Box.java
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/Box.class
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/CollisionDetector.java
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/CollisionDetector.class
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/TickTockCollision.html
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/TickTockCollision_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/TickTockCollision.java
/usr/java/j2sdk1.4.2/demo/java3d/TickTockCollision/TickTockCollision.class
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/Cube.java
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/Cube.class
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/PickHighlightBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/PickHighlightBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/Tetrahedron.java
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/Tetrahedron.class
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/TickTockPicking.java
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/TickTockPicking.class
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/TickTockPicking.html
/usr/java/j2sdk1.4.2/demo/java3d/TickTockPicking/TickTockPicking_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/Timer/TimerTest.java
/usr/java/j2sdk1.4.2/demo/java3d/Timer/TimerTest.class
/usr/java/j2sdk1.4.2/demo/java3d/Timer/TimerTest.html
/usr/java/j2sdk1.4.2/demo/java3d/Timer/TimerTest_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/README
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/ButtonPositionControls.class
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/ButtonPositionControls.java
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/HelloUniverse.class
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/HelloUniverse.java
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/PositionControls.class
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/PositionControls.java
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/RotationControls.class
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/RotationControls.java
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/SensorBehavior.class
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/SensorBehavior.java
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/VirtualInputDevice.class
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/VirtualInputDevice.java
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/WheelControls.class
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/WheelControls.java
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/HelloUniverse.html
/usr/java/j2sdk1.4.2/demo/java3d/VirtualInputDevice/HelloUniverse_plugin.html
/usr/java/j2sdk1.4.2/demo/java3d/geometry/p51_mustang.obj
/usr/java/j2sdk1.4.2/demo/java3d/geometry/p51_mustang.cg
/usr/java/j2sdk1.4.2/demo/java3d/geometry/galleon.obj
/usr/java/j2sdk1.4.2/demo/java3d/geometry/galleon.cg
/usr/java/j2sdk1.4.2/demo/java3d/geometry/gravel.int
/usr/java/j2sdk1.4.2/demo/java3d/geometry/minimart.obj
/usr/java/j2sdk1.4.2/demo/java3d/geometry/minimart.cg
/usr/java/j2sdk1.4.2/demo/java3d/geometry/window.inta
/usr/java/j2sdk1.4.2/demo/java3d/geometry/thdoor.inta
/usr/java/j2sdk1.4.2/demo/java3d/geometry/gas.rgb
/usr/java/j2sdk1.4.2/demo/java3d/geometry/pumps.int
/usr/java/j2sdk1.4.2/demo/java3d/geometry/minimart.mtl
/usr/java/j2sdk1.4.2/demo/java3d/geometry/products.rgb
/usr/java/j2sdk1.4.2/demo/java3d/geometry/numbers.int
/usr/java/j2sdk1.4.2/demo/java3d/geometry/brick2.int
/usr/java/j2sdk1.4.2/demo/java3d/geometry/concrete.int
/usr/java/j2sdk1.4.2/demo/java3d/geometry/beethoven.obj
/usr/java/j2sdk1.4.2/demo/java3d/images/apimage.jpg
/usr/java/j2sdk1.4.2/demo/java3d/images/bg.jpg
/usr/java/j2sdk1.4.2/demo/java3d/images/earth.jpg
/usr/java/j2sdk1.4.2/demo/java3d/images/stone.jpg
/usr/java/j2sdk1.4.2/demo/java3d/images/one.jpg
/usr/java/j2sdk1.4.2/demo/java3d/images/ttimage.jpg
/usr/java/j2sdk1.4.2/demo/java3d/images/animation1.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation2.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation3.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation4.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation5.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation6.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation7.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation8.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation9.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/animation10.gif
/usr/java/j2sdk1.4.2/demo/java3d/images/Java3d.jpg
/usr/java/j2sdk1.4.2/demo/java3d/index.html
/usr/java/j2sdk1.4.2/java3d-utils-src.jar
/usr/java/j2sdk1.4.2/jre/lib/ext/vecmath.jar
/usr/java/j2sdk1.4.2/jre/lib/ext/j3dcore.jar
/usr/java/j2sdk1.4.2/jre/lib/ext/j3dutils.jar
/usr/java/j2sdk1.4.2/jre/lib/ext/j3daudio.jar
/usr/java/j2sdk1.4.2/jre/lib/i386/libj3daudio.so
/usr/java/j2sdk1.4.2/jre/lib/i386/libJ3DUtils.so
/usr/java/j2sdk1.4.2/jre/lib/i386/libJ3D.so
/usr/java/j2sdk1.4.2/LICENSE-Java3D
/usr/java/j2sdk1.4.2/README-Java3D


%changelog
* Fri Nov  2 2001 Jim Callahan <jim@polaris.net>
- Initial build.


