// $Id: LogFormatter.java,v 1.1 2004/02/14 18:49:03 jim Exp $

package us.temerity.pipeline;

import java.util.Date;
import java.util.logging.*;
import java.text.*;

/*------------------------------------------------------------------------------------------*/
/*   L O G   F O R M A T T E R                                                              */
/*------------------------------------------------------------------------------------------*/

/** 
 * A standardized logging formatter for all log messages generated by Pipeline programs.
 */
public
class LogFormatter
  extends Formatter
{  
  /*----------------------------------------------------------------------------------------*/
  /*   C O N S T R U C T O R                                                                */
  /*----------------------------------------------------------------------------------------*/
  
  public 
  LogFormatter()
  {}


  /*----------------------------------------------------------------------------------------*/
  /*   F O R M A T                                                                          */
  /*----------------------------------------------------------------------------------------*/
  
  /**
   * Format the given log record and return the formatted string.
   *
   * @param record [<B>in</B>]
   *   The log record to be formatted.
   */ 
  public String 
  format
  (
   LogRecord record  
  ) 
  {
    SimpleDateFormat fmt = new SimpleDateFormat("E MMM dd HH:mm:ss z yyyy");
    String stamp = fmt.format(new Date(record.getMillis()));
    if(record.getLevel().equals(Level.SEVERE)) {
      return ("ERROR: " + stamp + sNL +
	      record.getMessage() + sNL);
    }
    else if(record.getLevel().equals(Level.WARNING)) {
      return ("WARNING: " + stamp + sNL +
	      record.getMessage() + sNL);
    }
    else if(record.getLevel().equals(Level.INFO)) {
      return (record.getMessage() + sNL);
    }
    else  {
      return ("DEBUG [" + record.getLevel().toString().toLowerCase() + "]: " + 
	      record.getMessage() + sNL);
    }
  }
  

  /*----------------------------------------------------------------------------------------*/
  /*   I N T E R N A L S                                                                    */
  /*----------------------------------------------------------------------------------------*/

  /** 
   * Cached line seperator.
   */ 
  private static String sNL = System.getProperty("line.separator", "\n");

}



