#--- RULES -----------------------------------------------------------------------------------

%:
	$(MAKE) -f Makefile.local -C MayaAnimInstanceBuildAction $@
	$(MAKE) -f Makefile.local -C ModelReplaceAction $@
	$(MAKE) -f Makefile.local -C MRayTextureGroupAction $@
	$(MAKE) -f Makefile.local -C MRayTextureGroupTool $@
	$(MAKE) -f Makefile.local -C ProjectSetterUpper $@
	$(MAKE) -f Makefile.local -C ShakeQuickTimeAction $@
	$(MAKE) -f Makefile.local -C ShakeQuickTimeThumbnailAction $@
